version: "3.8"
services:
  grpc-server:
    build: ./server
    ports:
      - "50051:50051"

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - GRPC_SERVER=grpc-server:50051