version: "3.8"
services:
  grpc-server:
    build: ./server
    ports:
      - "50051:50051"
    networks:
      - learning

  client:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - GRPC_SERVER=grpc-server:50051
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      pgdb:
        condition: service_healthy
    networks:
      - learning

  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - /Users/alexanderkucher/rebrain/db/data:/var/lib/postgresql/data
    networks:
      - learning

networks:
  learning:
    driver: bridge